### ISSUE TITLE
Possible Typo in ['PRP', 'VBG', 'VBZ']

### ISSUE THREAD

**Issue by JiaqiLiu** [indrajithi/genquest#7]
https://github.com/indrajithi/genquest/blob/b4e43531a9612ad09cce87791d6baeca6236207a/quest.py#L101

Hi, is there any possible typo here? I am not pretty sure, but there are two `VBG`.

**Comment by indrajithi** [comment]
Yes, that's a typo. Thanks for pointing that out. `line.words[bucket['VBG']]` is redundant here.
